In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot

In [2]:
data245_cleaneddata=pd.read_csv("https://raw.githubusercontent.com/Sowmyadiya/Data245-Project/master/Datasets/proj_data245_finaldata.csv")

In [3]:
data245_cleaneddata=data245_cleaneddata.drop(['Unnamed: 0'], axis = 1)

In [4]:
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import utils

In [5]:
final_data = pd.get_dummies(data = data245_cleaneddata, columns = ['company','title',
                                                             'tag'])
df = final_data.loc[ : , final_data.columns != 'state']

target_data=data245_cleaneddata['state']

In [6]:
# Run this program on your local python
# interpreter, provided you have installed
# the required libraries.

# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Function importing Dataset
def importdata():
	balance_data = pd.read_csv(
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data',
	sep= ',', header = None)
	
	# Printing the dataswet shape
	print ("Dataset Length: ", len(balance_data))
	print ("Dataset Shape: ", balance_data.shape)
	
	# Printing the dataset obseravtions
	print ("Dataset: ",balance_data.head())
	return balance_data

# Function to split the dataset
def splitdataset(balance_data):

	# Separating the target variable
	X = balance_data.values[:, 1:5]
	Y = balance_data.values[:, 0]

	# Splitting the dataset into train and test
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test
	
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):

	# Creating the classifier object
	clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

	# Performing training
	clf_gini.fit(X_train, y_train)
	return clf_gini
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):

	# Decision tree with entropy
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 3, min_samples_leaf = 5)

	# Performing training
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


# Function to make predictions
def prediction(X_test, clf_object):

	# Predicton on test with giniIndex
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	print(y_pred)
	return y_pred
	
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: ",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred))

# Driver code
def main():
	
	# Building Phase
	#data = importdata()
	Y = target_data
	X = df
	X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.30,random_state=42)
	clf_gini = train_using_gini(X_train, X_test, y_train)
	clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
	
	# Operational Phase
	print("Results Using Gini Index:")
	
	# Prediction using gini
	y_pred_gini = prediction(X_test, clf_gini)
	cal_accuracy(y_test, y_pred_gini)
	
	print("Results Using Entropy:")
	# Prediction using entropy
	y_pred_entropy = prediction(X_test, clf_entropy)
	cal_accuracy(y_test, y_pred_entropy)
	
	
# Calling main function
if __name__=="__main__":
	main()

Results Using Gini Index:
Predicted values:
['California' 'Washington' 'California' ... 'Washington' 'Oregon'
 'California']
Confusion Matrix:  [[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ... 3707    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Accuracy :  87.85249457700651


/Users/sowmya/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Report :                  precision    recall  f1-score   support

       Alabama       0.00      0.00      0.00         7
       Arizona       0.00      0.00      0.00       112
      Arkansas       0.00      0.00      0.00        37
    California       1.00      1.00      1.00      6853
      Colorado       0.00      0.00      0.00       159
   Connecticut       0.00      0.00      0.00        31
      Delaware       0.00      0.00      0.00        20
       Florida       1.00      1.00      1.00        72
       Georgia       0.32      1.00      0.49       165
         Idaho       0.00      0.00      0.00        16
      Illinois       0.00      0.00      0.00       241
       Indiana       0.00      0.00      0.00        32
          Iowa       0.00      0.00      0.00         7
        Kansas       0.00      0.00      0.00        11
      Kentucky       0.00      0.00      0.00         6
     Louisiana       0.00      0.00      0.00         8
         Maine       0.00      0.00  

/Users/sowmya/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Report :                  precision    recall  f1-score   support

       Alabama       0.00      0.00      0.00         7
       Arizona       0.00      0.00      0.00       112
      Arkansas       0.00      0.00      0.00        37
    California       1.00      1.00      1.00      6853
      Colorado       0.00      0.00      0.00       159
   Connecticut       0.00      0.00      0.00        31
      Delaware       0.00      0.00      0.00        20
       Florida       1.00      1.00      1.00        72
       Georgia       0.32      1.00      0.49       165
         Idaho       0.00      0.00      0.00        16
      Illinois       0.00      0.00      0.00       241
       Indiana       0.00      0.00      0.00        32
          Iowa       0.00      0.00      0.00         7
        Kansas       0.00      0.00      0.00        11
      Kentucky       0.00      0.00      0.00         6
     Louisiana       0.00      0.00      0.00         8
         Maine       0.00      0.00  

In [7]:
X = df

Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,target_data,test_size=0.30,random_state=42)
Ytrain

19949    California
22859    California
17930    California
10458    California
41775    Washington
            ...    
11284    California
44732    Washington
38158         Texas
860      California
15795    California
Name: state, Length: 36572, dtype: object

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve,auc

rnd_clf = RandomForestClassifier(n_estimators=16, max_leaf_nodes=60, random_state=70,criterion='gini')
rnd_clf.fit(Xtrain, Ytrain)

y_pred_rf = rnd_clf.predict(Xtest)
print(accuracy_score(Ytest, y_pred_rf))
y_pred_rf

0.8200842158989409


array(['California', 'Washington', 'California', ..., 'Washington',
       'Washington', 'California'], dtype=object)

In [9]:
import pickle
pickle_out=open("RandomForest_data245.pkl","wb")
pickle.dump(rnd_clf,pickle_out)
pickle_out.close()